use crate::save_file::SaveFile;


pub struct Pokemon {
    pub species_id: u8,
    pub current_hp: u16,
    pub level: u8,
    pub status: u8,
    pub pkmn_type_1: u8,
    pub pkmn_type_2: u8,
    pub catch_rate: u8,
    pub move_index1: u8,
    pub move_index2: u8,
    pub move_index3: u8,
    pub move_index4: u8,
    pub ot_id: u16,
    pub experience_pts: u32,
    pub hp_stat_exp: u16,
    pub attack_stat_exp: u16,
    pub defense_stat_exp: u16,
    pub speed_stat_exp: u16,
    pub special_stat_exp: u16,
    pub attack_iv: u8,
    pub defense_iv: u8,
    pub speed_iv: u8,
    pub special_iv: u8,
}

impl Pokemon {

    // All adition below will be rooting from this first offset. Begin of first party pokemon data.
    pub const FIRST_PKMN_OFFSET: usize = SaveFile::GEN1_PARTY_DATA_OFFSET + SaveFile::_GEN1_PARTY_START_TO_FIRST;

    // All of these constants can be added to the current pokemon's offset 
    // to locate the various data within the games pokemon data structure.
    // Example: (FIRST_PKMN_OFFSET + SPECIES_ID) yields the byte holding the species
    // id for the first party pokemon.
    pub const SPECIES_ID: usize = 0x00;
    pub const CURRENT_HP: usize = 0x01;
    pub const LEVEL: usize = 0x03;
    pub const STATUS: usize = 0x04;
    pub const TYPE_1: usize = 0x05;
    pub const TYPE_2: usize = 0x06;
    pub const CATCH_RATE: usize = 0x07;
    pub const MOVE_INDEX_1: usize = 0x08;
    pub const MOVE_INDEX_2: usize = 0x09;
    pub const MOVE_INDEX_3: usize = 0x0A;
    pub const MOVE_INDEX_4: usize = 0x0B;
    pub const OT_ID: usize = 0x0C;
    pub const EXPERIENCE_PTS: usize = 0x0E;
    pub const HP_STAT_EXP: usize = 0x11;
    pub const ATTACK_STAT_EXP: usize = 0x13;
    pub const DEFENSE_STAT_EXP: usize = 0x15;
    pub const SPEED_STAT_EXP: usize = 0x17;
    pub const SPECIAL_STAT_EXP: usize = 0x19;
    pub const IV_1: usize = 0x1B;
    pub const IV_2: usize = 0x1C;

    

    
    
    // Function to map pokemon species to ids
    pub fn get_species_name(id: u8) -> &'static str {

        const INVALID_SPECIES_NAME: &str = "Invalid/Unknown Species";

        match id {
            1   => "Rhydon",
            2   => "Kangaskhan",
            3   => "Nidoran♂",
            4   => "Clefairy",
            5   => "Spearow",
            6   => "Voltorb",
            7   => "Nidoking",
            8   => "Slowbro",
            9   => "Ivysaur",
            10  => "Exeggutor",
            11  => "Lickitung",
            12  => "Exeggcute",
            13  => "Grimer",
            14  => "Gengar",
            15  => "Nidoran♀",
            16  => "Nidoqueen",
            17  => "Cubone",
            18  => "Rhyhorn",
            19  => "Lapras",
            20  => "Arcanine",
            21  => "Mew",
            22  => "Gyarados",
            23  => "Shellder",
            24  => "Tentacool",
            25  => "Gastly",
            26  => "Scyther",
            27  => "Staryu",
            28  => "Blastoise",
            29  => "Pinsir",
            30  => "Tangela",
            31  => "MissingNo",
            32  => "MissingNo",
            33  => "Growlithe",
            34  => "Onix",
            35  => "Fearow",
            36  => "Pidgey",
            37  => "Slowpoke",
            38  => "Kadabra",
            39  => "Graveler",
            40  => "Chansey",
            41  => "Machoke",
            42  => "Mr. Mime",
            43  => "Hitmonlee",
            44  => "Hitmonchan",
            45  => "Arbok",
            46  => "Parasect",
            47  => "Psyduck",
            48  => "Drowzee",
            49  => "Golem",
            50  => "MissingNo",
            51  => "Magmar",
            52  => "MissingNo",
            53  => "Electabuzz",
            54  => "Magneton",
            55  => "Koffing",
            56  => "MissingNo",
            57  => "Mankey",
            58  => "Seel",
            59  => "Diglett",
            60  => "Tauros",
            61  => "MissingNo",
            62  => "MissingNo",
            63  => "MissingNo",
            64  => "Farfetch'd",
            65  => "Venonat",
            66  => "Dragonite",
            67  => "MissingNo",
            68  => "MissingNo",
            69  => "MissingNo",
            70  => "Doduo",
            71  => "Poliwag",
            72  => "Jynx",
            73  => "Moltres",
            74  => "Articuno",
            75  => "Zapdos",
            76  => "Ditto",
            77  => "Meowth",
            78  => "Krabby",
            79  => "MissingNo",
            80  => "MissingNo",
            81  => "MissingNo",
            82  => "Vulpix",
            83  => "Ninetales",
            84  => "Pikachu",
            85  => "Raichu",
            86  => "MissingNo",
            87  => "MissingNo",
            88  => "Dratini",
            89  => "Dragonair",
            90  => "Kabuto",
            91  => "Kabutops",
            92  => "Horsea",
            93  => "Seadra",
            94  => "MissingNo",
            95  => "MissingNo",
            96  => "Sandshrew",
            97  => "Sandslash",
            98  => "Omanyte",
            99  => "Omastar",
            100 => "Jigglypuff",
            101 => "Wigglytuff",
            102 => "Eevee",
            103 => "Flareon",
            104 => "Jolteon",
            105 => "Vaporeon",
            106 => "Machop",
            107 => "Zubat",
            108 => "Ekans",
            109 => "Paras",
            110 => "Poliwhirl",
            111 => "Poliwrath",
            112 => "Weedle",
            113 => "Kakuna",
            114 => "Beedrill",
            115 => "MissingNo",
            116 => "Dodrio",
            117 => "Primape",
            118 => "Dugtrio",
            119 => "Venomoth",
            120 => "Dewgong",
            121 => "MissingNo",
            122 => "MissingNo",
            123 => "Caterpie",
            124 => "Metapod",
            125 => "Butterfree",
            126 => "Machamp",
            127 => "MissingNo",
            128 => "Golduck",
            129 => "Hypno",
            130 => "Golbat",
            131 => "Mewtwo",
            132 => "Snorlax",
            133 => "Magikarp",
            134 => "MissingNo",
            135 => "MissingNo",
            136 => "Muk",
            137 => "MissingNo",
            138 => "Kingler",
            139 => "Cloyster",
            140 => "MissingNo",
            141 => "Electrode",
            142 => "Clefable",
            143 => "Weezing",
            144 => "Persian",
            145 => "Marowak",
            146 => "MissingNo",
            147 => "Haunter",
            148 => "Abra",
            149 => "Alakazam",
            150 => "Pidgeotto",
            151 => "Pidgeot",
            152 => "Starmie",
            153 => "Bulbasaur",
            154 => "Venusaur",
            155 => "Tentacruel",
            156 => "MissingNo",
            157 => "Goldeen",
            158 => "Seaking",
            159 => "MissingNo",
            160 => "MissingNo",
            161 => "MissingNo",
            162 => "MissingNo",
            163 => "Ponyta",
            164 => "Rapidash",
            165 => "Rattata",
            166 => "Raticate",
            167 => "Nidorino",
            168 => "Nidorina",
            169 => "Geodude",
            170 => "Porygon",
            171 => "Aerodactyl",
            172 => "MissingNo",
            173 => "Magnemite",
            174 => "MissingNo",
            175 => "MissingNo",
            176 => "Charmander",
            177 => "Squirtle",
            178 => "Charmeleon",
            179 => "Wartortle",
            180 => "Charizard",
            181 => "MissingNo",
            182 => "MissingNo",
            183 => "MissingNo",
            184 => "MissingNo",
            185 => "Oddish",
            186 => "Gloom",
            187 => "Vileplume",
            188 => "Bellsprout",
            189 => "Weepinbell",
            190 => "Victreebel",
            _ => INVALID_SPECIES_NAME
        }
    }
}

